dist: trusty
sudo: required
language: c

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -q
    - sudo apt-get install gcc-8 gfortran-8 -y
    - export CC=gcc-8
    - export FC=gfortran-8
    - ${FC} --version

install:
    - mkdir build && cd build
    - cmake ..
    - make VERBOSE=1

script:
    - ctest -V -R short
